server.port: 8080

puriflow4j:
  mode: mask               # dry-run | mask | strict
  detectors:
    - email
    - jwt
    - password
    - aws-key
    - authorization
    - credit-card

  logs:
    enabled: true
    only-loggers: []       # if empty - all
    ignore-loggers: []     # ignore by prefix/full name
    key-allowlist: [traceId,requestId,correlationId]  # never mask these keys
    key-blocklist:  [] # force mask

management.endpoints.web.exposure.include: "*"
